---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dashboard-hpa
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    kind: Deployment
    name: mydeploy
  targetCPUUtilizationPercentage: 60
