apiVersion: v1
kind: Service
metadata: 
  name: nginxsvc 
  labels: 
    service: nginx 
spec:
  selector: 
    app: nginx
  type: ClusterIP #NodePort / LoadBalancer 
  ports: 
    - name: myport 
      port: 80 
      targetPort: 80 
      protocol: TCP
