apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: myrs 
  labels: 
    app: nginx
    layer: web
    version: "1.23"
spec:
  minReadySeconds: 3
  replicas: 3
  selector: 
    matchLabels:
      app: nginx
  template:
    metadata:
      name: mypod 
      labels: 
        app: nginx
    spec:
      containers:
        - name: mycon 
          image: nginx:1.23
          ports:
            - containerPort: 80