apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: myrs 
  labels:
    sangmesh: sang 
spec:
  minReadySeconds: 3
  replicas: 3
  selector: 
    matchLabels:
      gheware: ghe 
  template:
    metadata: 
      name: mypod 
      labels: 
        gheware: ghe 
    spec:
      containers:
        - name: mycon 
          image: alpine 
          args: 
            - sleep
            - 1d

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    gheware: ghe
  type: ClusterIP
  clusterIP: None
  ports:
    - name: nginx-svc
      port: 80
      targetPort: 80
      protocol: TCP


