---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dashboard-hpa
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    kind: Deployment
    name: dashboard-deploy
  targetCPUUtilizationPercentage: 60
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-deploy
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: dashboard
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: dashboard-pod
      labels:
        app: dashboard
        version: "1.0.0"
      spec:
        containers:
          - name: dashboard
            image: shaikkhajaibrahim/dashboardservice:1.0.0
            ports:
              - containerPort: 80