apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  template:
    metadata:
      name: mypod
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mycon
          image: alpine
          args:
            - sleep
            - 3s