
#--------------------------------------------------------------------------------------------------------------------
#probe using exec 

apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: myrs 
  labels:
    level: myrs
spec: 
  minReadySeconds: 1
  replicas: 3
  selector: 
    matchLabels:
      app: httpd
  template: 
    metadata:
      name: mypod 
      labels: 
        app: httpd
    spec:
      containers:
        - name: mycon 
          image: httpd:2.4.57
          ports: 
            - containerPort: 80
          livenessProbe: 
            failureThreshold: 1
            initialDelaySeconds: 1
            periodSeconds: 1
            successThreshold: 1
            exec: 
              command: 
                - pwd 
          readinessProbe:
            failureThreshold: 1
            initialDelaySeconds: 1
            periodSeconds: 1
            successThreshold: 1
            exec: 
              command: 
                - pwd 
                
#-----------------------------------------------------------------------------------------------------      
#-----------------------------------------------------------------------------------------------------    
#-----------------------------------------------------------------------------------------------------    

#probe using http code 
#--------------------------------------------------------------------------------------------------       

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: https-rs
  labels:
    app: httpd
spec:
  minReadySeconds: 1
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      name: httpd
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd:2.4.57
          ports:
            - containerPort: 80
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              path: /
              port: 80
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              path: /
              port: 80