apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: myrs 
  labels:
    sangmesh: sang 
spec:
  minReadySeconds: 3
  replicas: 3
  selector: 
    matchLabels:
      gheware: ghe 
  template:
    metadata: 
      name: mypod 
      labels: 
        gheware: ghe 
    spec:
      imagePullSecrets: 
        - name:  myregistrykey
      containers:
        - name: mycon 
          image: gheware/sangam:latest
          args: 
            - sleep
            - 1d



--- 

apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: awesomeapps
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogIloyaGxkMkZ5WlRwQU1VMXFNVFZoWlRBNE1RPT0iCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQp9
type: kubernetes.io/dockerconfigjson


