apiVersion: v1
kind: ReplicationController
metadata: 
  name: myrc
  labels: 
    sangmesh: sang
spec:
  replicas: 3
  minReadySeconds: 3
  selector:
    gheware: ghe 
  template: 
    metadata:
      name: mypod 
      labels:
        gheware: ghe
    spec:
      containers:
        - name: mycon 
          image: alpine
          args:
            - sleep 
            - 1d
        