apiVersion: v1
kind: Secret
metadata: 
  name: mysecret 
  labels: 
    sang: ghe
data: 
  sangamesh: Z2hld2FyZQo=
  sangamesh1: Z2hld2FyZTEK
  sangamesh2: Z2hld2FyZTIK
  sangamesh3: Z2hld2FyZTMK

---

apiVersion: v1
kind: Pod
metadata: 
  name: mypod
  labels: 
    sang: ghe 
spec: 
  containers: 
    - name: mycon 
      image: alpine
      envFrom: 
        - secretRef: 
            name: mysecret
            optional: false
      args:
        - sleep
        - 1d


#----------------------------------
#using only env one env seperatly 
---

apiVersion: v1
kind: Secret
metadata: 
  name: mysecret 
  labels: 
    sang: ghe
data: 
  sangamesh: Z2hld2FyZQo=
  sangamesh1: Z2hld2FyZTEK
  sangamesh2: Z2hld2FyZTIK
  sangamesh3: Z2hld2FyZTMK
---

apiVersion: v1
kind: Pod
metadata: 
  name: mypod
  labels: 
    sang: ghe 
spec: 
  containers: 
    - name: mycon 
      image: alpine
      env: 
        - name: SANGAMESH
          valueFrom: 
            secretRef: 
              key: sangamesh
              name: mysecret
        - name: SANGAMESH1
          valueFrom: 
            secretRef: 
              key: sangamesh1
              name: mysecret
      
      args:
        - sleep
        - 1d





