apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: nginx
  labels: 
    sang: ghe
spec: 
  replicas: 3
  selector: 
    app: nginx 
  template: 
    metadata: 
      name: mypod 
      labels: 
        app: nginx 
    spec:
      containers: 
        - name: mycon 
          image: nginx
          ports:
            - containerPort: 80 
          volumeMounts: 
            - name: htmlhome 
              readOnly: false 
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates: 
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata: 
        name: myvolclaim 
      spec: 
        accessModes: 
          - ReadWriteOnce
        resources: 
          requests:
            storage: 1Gi
        storageClassName: managed

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  type: ClusterIP
  clusterIP: None
  ports:
    - name: nginx-svc
      port: 80
      targetPort: 80
      protocol: TCP

